### ISSUE TITLE
1.1.0 causes UUID error

### ISSUE THREAD

**Issue by normen** [lucavb/homebridge-http-motion-sensor#6]
Updating to 1.1.0 causes my homebridge server to crash on boot because of a supposed UUID mismatch.. Something seems to go wrong with setting the accessory names.

The setup booted fine before with the same config:
```
        {
            "name": "Melder Eingang",
            "port": 8301,
            "accessory": "http-motion-sensor"
        },
        {
            "name": "Melder Indy",
            "port": 8302,
            "accessory": "http-motion-sensor"
        }
```

Heres the Error stack trace, for both accessories it's the same UUID:
```
Feb 14 21:56:31 homebridge homebridge[28515]: [2020-2-14 21:56:31] [Melder Eingang] Initializing http-motion-sensor accessory...
Feb 14 21:56:31 homebridge homebridge[28515]: [2020-2-14 21:56:31] Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000023-0000-1000-8000-0026BB765291
Feb 14 21:56:31 homebridge homebridge[28515]:     at AccessoryInformation.Service._this.addCharacteristic (/usr/local/lib/node_modules/homebridge-http-motion-sensor/node_modules/hap-nodejs/dist/lib/Service.js:79:27)
Feb 14 21:56:31 homebridge homebridge[28515]:     at new AccessoryInformation (/usr/local/lib/node_modules/homebridge-http-motion-sensor/node_modules/hap-nodejs/dist/lib/gen/HomeKit.js:3332:15)
Feb 14 21:56:31 homebridge homebridge[28515]:     at HomebridgeHttpMotionSensor.prepareServices (/usr/local/lib/node_modules/homebridge-http-motion-sensor/dist/index.js:30:36)
Feb 14 21:56:31 homebridge homebridge[28515]:     at new HomebridgeHttpMotionSensor (/usr/local/lib/node_modules/homebridge-http-motion-sensor/dist/index.js:21:14)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Feb 14 21:56:31 homebridge homebridge[28515]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Module._compile (internal/modules/cjs/loader.js:701:30)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Module.load (internal/modules/cjs/loader.js:600:32)
Feb 14 21:56:31 homebridge homebridge[28515]:     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
Feb 14 21:56:31 homebridge homebridge[28515]:     at startup (internal/bootstrap/node.js:283:19)
Feb 14 21:56:31 homebridge homebridge[28515]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Feb 14 21:56:31 homebridge homebridge[28515]: Uncaught exception error:  Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000023-0000-1000-8000-0026BB765291
Feb 14 21:56:31 homebridge homebridge[28515]:     at AccessoryInformation.Service._this.addCharacteristic (/usr/local/lib/node_modules/homebridge-http-motion-sensor/node_modules/hap-nodejs/dist/lib/Service.js:79:27)
Feb 14 21:56:31 homebridge homebridge[28515]:     at new AccessoryInformation (/usr/local/lib/node_modules/homebridge-http-motion-sensor/node_modules/hap-nodejs/dist/lib/gen/HomeKit.js:3332:15)
Feb 14 21:56:31 homebridge homebridge[28515]:     at HomebridgeHttpMotionSensor.prepareServices (/usr/local/lib/node_modules/homebridge-http-motion-sensor/dist/index.js:30:36)
Feb 14 21:56:31 homebridge homebridge[28515]:     at new HomebridgeHttpMotionSensor (/usr/local/lib/node_modules/homebridge-http-motion-sensor/dist/index.js:21:14)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Feb 14 21:56:31 homebridge homebridge[28515]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Module._compile (internal/modules/cjs/loader.js:701:30)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Module.load (internal/modules/cjs/loader.js:600:32)
Feb 14 21:56:31 homebridge homebridge[28515]:     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Feb 14 21:56:31 homebridge homebridge[28515]:     at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
Feb 14 21:56:31 homebridge homebridge[28515]:     at startup (internal/bootstrap/node.js:283:19)
Feb 14 21:56:31 homebridge homebridge[28515]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```

**Comment by lucavb** [comment]
Would have been so nice if the transition would have just gone smoothly. 🙃 Seems like you no longer need the AccessoryInformation Service. Currently on questionable Internet so I can't commit for another 30 minutes. I'll release a new version then. Thanks for posting the issue :)

**Comment by lucavb** [comment]
Released 1.1.1. Can you check if that fixed it?

**Comment by normen** [comment]
Nah, now it's some import?
```
ERROR LOADING PLUGIN homebridge-http-motion-sensor:
[2020-2-14 23:08:38] Error: Cannot find module 'hap-nodejs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-http-motion-sensor/dist/index.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by lucavb** [comment]
So sorry about that. That should also be fixed now. I just tested it and I was able to fire up homebridge with your configuration. The only thing I couldn't test was whether it triggers the status change (the http server itself works).

**Comment by normen** [comment]
Hehe, no worries, I still had my branch I could link in quickly when the boot failed.

Yeah, this version works but I had to re-assign all automation triggers, for some reason the devices got reset. Funnily they kept the room assignment which they usually also lose.

It could be that the error didn't crash homebridge and it booted through without those devices, which makes HomeKit forget them. But maybe you made other changes with the device IDs or somesuch?

**Comment by lucavb** [comment]
Well, it would appear like I used a wrong type definition for the service and thus called the constructor in an inappropriate way. Anyway, not sure if that fixes it, but seems like a good idea anyway.

**Comment by normen** [comment]
I had to re-assign again with the 1.1.4 version but everything seems to be working, cheers!

**Comment by lucavb** [comment]
My pleasure, was fun to rewrite it in TypeScript.
